<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="eli_5-PC" name="com.scp.demos.Selenium.TestOrangeHRM" tests="5" failures="0" timestamp="6 Aug 2017 07:45:19 GMT" time="63.160" errors="1">
  <testcase name="testLogin" time="11.097" classname="com.scp.demos.Selenium.TestOrangeHRM">
    <error type="junit.framework.ComparisonFailure" message="expected:&lt;.../password...&gt; but was:&lt;......&gt;">
      <![CDATA[junit.framework.ComparisonFailure: expected:<.../password...> but was:<......>
	at junit.framework.Assert.assertEquals(Assert.java:81)
	at junit.framework.Assert.assertEquals(Assert.java:87)
	at com.scp.demos.Selenium.TestOrangeHRM.testLogin(TestOrangeHRM.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </error>
  </testcase> <!-- testLogin -->
  <testcase name="testLogin" time="12.347" classname="com.scp.demos.Selenium.TestOrangeHRM"/>
  <testcase name="testLogin" time="10.404" classname="com.scp.demos.Selenium.TestOrangeHRM"/>
  <testcase name="testLogin" time="17.149" classname="com.scp.demos.Selenium.TestOrangeHRM"/>
  <testcase name="testLogin" time="12.163" classname="com.scp.demos.Selenium.TestOrangeHRM"/>
</testsuite> <!-- com.scp.demos.Selenium.TestOrangeHRM -->
